In [2]:
import torch

%load_ext rich

The rich extension is already loaded. To reload it, use:
  %reload_ext rich


In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)
x.grad

In [7]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [9]:
x.grad == 4*x

tensor([True, True, True, True])

In [10]:
x.grad.zero_()

y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [12]:
x.grad.zero_()
y = x*x
y.backward(gradient=torch.ones(len(y)))
x.grad

tensor([0., 2., 4., 6.])