In [1]:
%reload_ext rich

In [2]:
import torch

In [4]:
torch.__version__

'2.10.0'

# Basics

In [6]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
X = x.reshape(-1,4)
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.randn(3,4)


tensor([[ 0.2816,  0.3382,  1.6553,  2.6606],
        [ 1.3383, -2.2648,  0.4345,  0.1911],
        [ 0.1299,  1.1362,  0.2584,  0.2231]])

In [12]:
X[-1],X[1:]


(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

In [14]:
X = torch.arange(12,dtype=torch.float32).reshape(3,-1)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y),dim=0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [15]:
torch.cat((X,Y),dim=1)


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [16]:
X == Y


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
X.sum()

tensor(66.)

# Broadcasting

In [20]:
a = torch.arange(3).reshape(3,-1)
b = torch.arange(2).reshape(1,-1)
a,b


(tensor([[0],
        [1],
        [2]]), tensor([[0, 1]]))

In [21]:
a+b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
torch.tensor([[0,0],[1,1],[2,2]])+torch.tensor(([0,1],[0,1],[0,1]))


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [26]:

Y = X+Y

In [25]:
Y


tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])